version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    image: hyper-tension-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hyper-tension-bot
    depends_on:
      - mongodb
    environment:
      - TELEGRAM_BOT_TOKEN=6484731080:AAEvP8_0pvlAWqx2b3Lj1qESwU0WgrAGUtM
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017

volumes:
  mongo-data:
