name: dockerify
on:
  push:
    branches:
      - master
      - main
      - develop
      - version/*
  workflow_dispatch:
env:
  PROJECT_NAME: hyper-tension-bot
  WORKFLOW: dockerify
  RETRY_TIME: 5m
  MAX_RETRIES: 3
jobs:
  dockerify:
    runs-on: ubuntu-latest
    name: Dockerify
    steps:
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all history
          submodules: recursive

      - name: Get All Tags
        run: git fetch --tags -f

      - name: Get Version
        id: get-version
        run: echo ::set-output name=version::$(python setup.py get_project_version | tail -n 1)
        
      - name: Generate appsettings.json
        run: |
          cd src/HyperTensionBot.Server
          ruby generate_appsettings.rb
        env:
          SECRET_TELEGRAM_TOKEN: ${{ secrets.SECRET_TELEGRAM_TOKEN }}
          SECRET_KEY_OPENAI: ${{ secrets.SECRET_KEY_OPENAI }}

      - name: Create Docker Image
        run: |
          cd src/HyperTensionBot.Server
          ../../.github/scripts/retry.sh "docker-compose -f docker-compose.yml build"
          ../../.github/scripts/retry.sh "docker tag ${{env.PROJECT_NAME}} pikalab/${{env.PROJECT_NAME}}:${{ steps.get-version.outputs.version }}"
        shell: bash

      - name: Push Image on Docker Hub
        run: docker push pikalab/${{env.PROJECT_NAME}}:${{ steps.get-version.outputs.version }}